spring:
  datasource:
    url: jdbc:h2:tcp://localhost/~/jpa_shop
    username: sa
    password:
    driver-class-name: org.h2.Driver

  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
#        show_sql: true
        format_sql: true
        default_batch_fetch_size: 100

  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html

logging:
  level:
    org.hibernate.SQL: debug
#    org.hibernate.type: trace

decorator:
  datasource:
    p6spy:
      enable-logging: true
      multiline: true
      logging: slf4j
